#!/usr/bin/env python3

from webview_controller import Controller


#! this script will be used as the
#! entry point for the application

if __name__ == '__main__':
    controller = Controller()
    controller.run()
